//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metra_Development.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metra_Development.Resources.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენს შესხებ.
        /// </summary>
        public static string NavAboutUs {
            get {
                return ResourceManager.GetString("NavAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბლოგი.
        /// </summary>
        public static string NavBlog {
            get {
                return ResourceManager.GetString("NavBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტი.
        /// </summary>
        public static string NavContact {
            get {
                return ResourceManager.GetString("NavContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი გვერდი.
        /// </summary>
        public static string NavMain {
            get {
                return ResourceManager.GetString("NavMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიახლეები.
        /// </summary>
        public static string NavNews {
            get {
                return ResourceManager.GetString("NavNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტები.
        /// </summary>
        public static string NavProject {
            get {
                return ResourceManager.GetString("NavProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «მეტრა დეველოპმენტი».
        /// </summary>
        public static string SlaiderName {
            get {
                return ResourceManager.GetString("SlaiderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კეთილდღეობა იზომება რიცხვებში.
        /// </summary>
        public static string SlaiderWord {
            get {
                return ResourceManager.GetString("SlaiderWord", resourceCulture);
            }
        }
    }
}
